---
name: Mouse2Touch
author: clau
category: Utilities
tags: [iphone, ipad, safari, multitouch]
docs: http://tabqwerty.com/2010/04/08/supporting-mouse-events-in-mobile-safari.html
demo: http://www.mikematas.com
current: 0.1